import { products } from "../components/Card/data/products";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Product from "../components/card/Product";

//https://jsonplaceholder.typicode.com/photos

export const getStaticProps = async () => {
  // Fetching data from jsonplaceholder.
  // const res = await fetch("https://jsonplaceholder.typicode.com/photos&quot;);
  // let allAlbums = await res.json();

  return {
    // props: allAlbums,
    props: {
      productList: products,
      // productList: allAlbums.map((album) => album),
    },
  };
};

export default function Home({ productList }) {
  console.log(productList);
  return (
    <div className={styles.container}>
      <Head>
        <title>Shopping Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen flex justify-center items-center p-5 md:grid-cols-2;">
        <div className="grid grid-cols-1 mt-6 gap-y-10 gap-x-6 lg:grid-cols-3 md:grid-cols-2 xl:grid-cols-4">
          {productList.map((product) => (
            <Product
              key={product.Id}
              productId={product.Id}
              propductName={product.name}
              productImage={product.url}
              productDescription={product.description}
              productPrice={product.price}
            />
          ))}{" "}
        </div>
      </div>
    </div>
  );
}
