import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Product from "../components/card/Product";

//https://jsonplaceholder.typicode.com/photos

export const getStaticProps = async () => {
  // Fetching data from jsonplaceholder.
  var res = "../components/Card/data/product.json";
  let all = res.json;
  // Sending fetched data to the page component via props.
  return {
    props: all,
    props: {
      list: [all].map((res) => res),
    },
  };
};

export default function Home({ list }) {
  // console.log(productList);
  return (
    <div className={styles.container}>
      <Head>
        <title>Shopping Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen flex justify-center items-center p-5 md:grid-cols-2;">
        <div className="grid grid-cols-1 mt-6 gap-y-10 gap-x-6 lg:grid-cols-3 md:grid-cols-2 xl:grid-cols-4">
          {[list].map((product) => (
            <div>
              <Product
                productId={product.Id}
                propductName={product.name}
                productImage={product.url}
                productDescription={product.description}
                productPrice={product.price}
              />
            </div>
          ))}
          //{" "}
        </div>
      </div>
    </div>
  );
}
